apiVersion: automation.cloudbees.io/v1alpha1
kind: workflow
name: build-and-push
on:
  workflow_call:
    inputs:
      imageName:
        type: string
        required: true
      imageTag:
        type: string
        required: true
      registryUsername:
        type: string
        required: true
      registryToken:
        type: string
        required: true

jobs:
  build:
    steps:
      - uses: cloudbees-io/checkout@v1
        name: Get source code
        kind: build
        continue-on-error: true
      - uses: cloudbees-io/configure-oci-credentials@v1
        name: Configure container registry credentials
        continue-on-error: true
        id: dockerconfig
        with:
          registry: https://index.docker.io/v1/
          username: ${{ inputs.registryUsername }}
          password: ${{ inputs.registryToken }}
      - uses: cloudbees-io/kaniko@v1
        name: Build container image
        kind: build
        with:
          destination: ${{ inputs.imageName }}:${{ inputs.imageTag }},${{ inputs.imageName }}:latest
          tar-path: container-image.tar
          build-args: BUILDKIT_CONTEXT_KEEP_GIT_DIR=1,BUILDKIT_INLINE_CACHE=1
      - uses: calculi-corp/assets-plugin-chain-utils/upload-binary@v1
        name: Upload binary from container build
        continue-on-error: true
        id: upload-binary
        with:
          file-path: container-image.tar
          file-type: BINARY_CONTAINER
          debug: "true"
      - name: Publish evidence
        uses: cloudbees-io/publish-evidence-item@v1
        with:
          content: |-
            ## Built and pushed image to docker hub
            
            [Docker Hub](https://hub.docker.com/repository/docker/${{ inputs.imageName }}/tags)
            
            Deployed ${{ inputs.imageName }}:${{ inputs.imageTag }}
          format: MARKDOWN 